[project]
name = "mir-commander"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cclib>=1.8.1",
    "numpydantic>=1.6.9",
    "pillow>=11.3.0",
    "pydantic>=2.11.4",
    "pydantic-extra-types>=2.10.5",
    "pyopengl>=3.1.9",
    "pyside6>=6.9.1",
    "pyyaml>=6.0.2",
]

[project.scripts]
mircmd = "mir_commander.__main__:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "pre-commit>=4.3.0",
    "pre-commit-hooks>=6.0.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.9",
    "types-pyyaml>=6.0.12.20250822",
]

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [".venv", "tmp"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
